### ISSUE TITLE
discussion

### ISSUE THREAD

**Issue by sarbbottam** [jonathanewerner/webpack-validator#5]
* ~~why the tests are scattered across `test/` and `src/**/*.test.js`~~?
* can all the tests be moved to `test/`? `npm test` command will get simplified then.
* ~~should we use `ava` (in built es6 support) instead of `mocha`~~?

**Comment by kentcdodds** [comment]
I'm fine either way. In applications it's nice to co-locate test files, but in smaller libraries, it's not as necessary.

I prefer AVA, but I like mocha. ¯\\\_(ツ)_/¯

**Comment by jonathanewerner** [comment]
Hey,
so `test` only contains utils/files for tests, whereas the real tests are siblings to the files tested. I like this approach because it reduces the mental burden to write new tests when you create new directory structures, as you don't have to mirror them in the `test` directory.

I'm not convinced by the ES6 argument for ava, as a `babel-polyfill` is still necessary to get everything we / I want from transpilation (was also the case in kents repo), so the difference is negligible here i think.
Main reason for me wanting to stay with mocha *at the moment* is watch reload speed, its like 60ms for mocha vs 1-2 sec for ava when i compare the test-suites of kentcdodds/webpack-validator and jonathanewerner/webpack-validator.  
I also am not a great fan of the `t.ok` syntax for power-assert, i think `assert(stuff)` is cleaner. Thats bike-shedding though. :)

**Comment by sarbbottam** [comment]
Thanks for sharing your views, I have updated the original description :smile:
I would request you to have a look at  a PR (will raise it later sometimes today) which would isolate the `tests` in `test/`, if it looks ok, we can take it forward from there, otherwise close this issue and the PR.

**Comment by sarbbottam** [comment]
>>* can all the tests be moved to `test/`? `npm test` command will get simplified then.

Nope, please see @jonathanewerner comment at https://github.com/jonathanewerner/webpack-validator/pull/7
