### ISSUE TITLE
Change Joi.assert() to Joi.validate()

### ISSUE THREAD

**Issue by nyrosmith** [jonathanewerner/webpack-validator#54]
I am implementeng the CLI right now and found some issues due to current behavior of webpack-validator.
Joi.assert() throws errors. As you can see in the screenshot of the readme the callstack gets printed. I think this is bad because as a user I'd think that I hit a bug. Joi.assert stops asserting after the first error, so you never get the real validation result. All remaining values are untested...

Switching to Joi.validate would fix this behavior and would make things ways more easier for the CLI which basically just calls webpack-validator. I have to make weird error catching and reformating the messages...

This would be a **breaking change** in terms of no more throwing errors.
@jonathanewerner If this change is ok for you I'd make a pull request

**EDIT:** I would make throwing errors configurable

**Comment by jonathanewerner** [comment]
Mh. I do like that `Joi.validate` allows customizing via options (`{abortEarly: false}`). I haven't found a way to get the nice toString output, where it shows you where the error occurs in your supplied object (as can be seen in the screenshot) -- that's the original reason i went for `.assert`. I have not investigated deeply, though.

I don't think error throwing should be optional for the webpack-validator package, as throwing errors is pretty essential here because else the build would just continue and you might not even notice. (This is especially important in CI contexts, where you don't even look at the console out most of the time.)

For `webpack-validator-cli` it's a different story as you might use it interactively and will notice the possible error *even if no error is thrown*. So making it configurable here seems sensible (i think opting out makes more sense though).

**Comment by nyrosmith** [comment]
I'll make a PR according to your mentions. I think discussing based on code is easier

**Comment by nyrosmith** [comment]
Btw I think we don't don't need to throw the error for CI. Setting the correct exit code should be enough afaik

**Comment by nyrosmith** [comment]
As discussed in the PR we will restructure the project so this change is no longer needed.
